version: '3.8'
services:
  basket:
    image: nicolasfy/basket:1.0
    container_name: basket
    restart: always 
    networks:
      - miage-corp
    depends_on:
      - keycloak
  backforfront:
    image: nicolasfy/backforfront:1.0
    container_name: backforfront
    ports:
      - "5100:80"
    restart: always 
    networks:
      - miage-corp
    depends_on:
      - keycloak
      - basket
  keycloak:
    image: jboss/keycloak:10.0.2
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
    restart: always 
    networks:
      - miage-corp
networks:
  miage-corp:
    name: miage-corp